spring:
  application:
    name: greeting-service
# Configurações do Actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"
